services:
  jupyter:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/home/jovyan/
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="